### ISSUE TITLE
Application not being updated

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#6]
Hi Anthony, 

It's been about a couple a hours since I have updated  and committed my code on GitHub, but it looks like those changes are not reflected on the application. For instance,  I have even changed a simple field label  and it's not being updated.  I first  thought it was my cache, but after disabling it did not solve problem. 

Can you look into this?

Thank you.

**Comment by ayoung8** [comment]
Romario,
The app stops deploying because you deleted the connection parsing in c8ab3ac34f6c577eca92f819e999fb6259870751 
This caused an conflict in your versions when you since you no longer have a connection.

You can revert your changes or if you need more help debugging please have Colette or Jane email me.

**Comment by romariochuela** [comment]
Great thanks.
